# Generated by Django 4.2.4 on 2023-08-17 20:46

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
                ("link", models.URLField()),
            ],
        ),
    ]
