# Generated by Django 4.2.4 on 2023-09-04 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("english", "0006_rename_review_bookreview_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("article_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("cover", models.ImageField(blank=True, upload_to="article_covers/")),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Poem",
            fields=[
                ("poem_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cover", models.ImageField(blank=True, upload_to="covers/")),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                ("story_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("cover", models.ImageField(blank=True, upload_to="story_covers/")),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="StoryReview",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("review", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ]
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "story_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="english.story"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PoemReview",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("review", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ]
                    ),
                ),
                (
                    "poem_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="english.poem"
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ArticleReview",
            fields=[
                ("review_id", models.AutoField(primary_key=True, serialize=False)),
                ("review", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[
                            (1, "1 star"),
                            (2, "2 stars"),
                            (3, "3 stars"),
                            (4, "4 stars"),
                            (5, "5 stars"),
                        ]
                    ),
                ),
                (
                    "article_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="english.article",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
